# -*- coding: utf-8 -*-
"""titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JtGVFdK-Kue09kezLXFtiWjFccL5y0Wg
"""

import seaborn as sns
df=sns.load_dataset('titanic')
df.head()

df.describe()

sns.scatterplot(df[['fare','age']])

ndf.tail()

# which gender had a greater presence on the boat
df[df['sex']=='male'].count()

df[df['sex']=='female'].count()

sns.countplot(x='sex',data=df)

# which passenger class had the least number of passengers
# hue :
import matplotlib.pyplot as plt
plt.figure(figsize=(10,4))
sns.countplot(x='class',data=df,hue='survived')

# was the number of passenger who survived greater or less than the number of passengers who did not survive
sns.countplot(x='survived',data=df)

# from which town most number of passengers embarked
sns.countplot(x='embark_town',data=df)

# how did the survival rate differ between males and females?
sns.countplot(x='sex',data=df,hue='survived')

# which class passenger did not survive in more number
sns.countplot(x='class',data=df,hue='survived')

# which town embarked passengers survived least in number
sns.countplot(x='embark_town',data=df,hue='survived')

# avg fare was high for which gender
sns.barplot(x='sex',y='fare',data=df)
# sns.baplot(x='sex',y='fare',ci=False)

# explore the relation between fare and survival
plt.figure(figsize=(10,4))
sns.barplot(x='survived',y='fare',data=df)

# explore relation between age and survival
sns.pointplot(data=df,x='survived',y='age')

